name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Set remote URL
        env:
          HF_TOKEN: ${{ secrets.RUTUJA_TOKEN }}
        run: git remote set-url origin https://Rutuja28:${{ secrets.RUTUJA_TOKEN }}@huggingface.co/spaces/Rutuja28/New_space
      - name: Pull from remote
        run: git pull origin main
      - name: Push to Hugging Face
        run: git push origin main
